# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_image_markup(object):
    def setupUi(self, image_markup):
        image_markup.setObjectName("image_markup")
        image_markup.resize(450, 380)
        image_markup.setBaseSize(QtCore.QSize(0, 0))
        image_markup.setStyleSheet("background-color:rgb(236, 236, 236)")
        self.centralwidget = QtWidgets.QWidget(image_markup)
        self.centralwidget.setObjectName("centralwidget")
        self.mark_up_btn = QtWidgets.QPushButton(self.centralwidget)
        self.mark_up_btn.setGeometry(QtCore.QRect(230, 290, 181, 31))
        self.mark_up_btn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;")
        self.mark_up_btn.setObjectName("mark_up_btn")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(30, 20, 371, 251))
        self.image.setObjectName("image")
        self.get_img_btn = QtWidgets.QPushButton(self.centralwidget)
        self.get_img_btn.setGeometry(QtCore.QRect(30, 290, 181, 31))
        self.get_img_btn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;")
        self.get_img_btn.setObjectName("get_img_btn")
        self.edit_btn = QtWidgets.QPushButton(self.centralwidget)
        self.edit_btn.setGeometry(QtCore.QRect(30, 290, 181, 31))
        self.edit_btn.setStyleSheet("background-color: rgb(255, 255, 255) ;\n"
"border-radius: 5px;\n"
"")
        self.edit_btn.setObjectName("edit_btn")
        self.done_btn = QtWidgets.QPushButton(self.centralwidget)
        self.done_btn.setGeometry(QtCore.QRect(230, 290, 181, 31))
        self.done_btn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"")
        self.done_btn.setObjectName("done_btn")
        self.done_btn.raise_()
        self.edit_btn.raise_()
        self.mark_up_btn.raise_()
        self.image.raise_()
        self.get_img_btn.raise_()
        image_markup.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(image_markup)
        self.statusbar.setObjectName("statusbar")
        image_markup.setStatusBar(self.statusbar)

        self.retranslateUi(image_markup)
        self.get_img_btn.clicked.connect(self.image.clear) # type: ignore
        self.edit_btn.clicked.connect(self.edit_btn.close) # type: ignore
        self.done_btn.clicked.connect(self.edit_btn.close) # type: ignore
        self.done_btn.clicked.connect(self.done_btn.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(image_markup)

    def retranslateUi(self, image_markup):
        _translate = QtCore.QCoreApplication.translate
        image_markup.setWindowTitle(_translate("image_markup", "image markup"))
        self.mark_up_btn.setText(_translate("image_markup", "Mark up"))
        self.image.setText(_translate("image_markup", "<center> Your photo </center>"))
        self.get_img_btn.setText(_translate("image_markup", "Open"))
        self.edit_btn.setText(_translate("image_markup", "Edit"))
        self.done_btn.setText(_translate("image_markup", "Done"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    image_markup = QtWidgets.QMainWindow()
    ui = Ui_image_markup()
    ui.setupUi(image_markup)
    image_markup.show()
    sys.exit(app.exec_())
