# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'save_question.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Save_question(object):
    def setupUi(self, Save_question):
        Save_question.setObjectName("Save_question")
        Save_question.resize(350, 150)
        Save_question.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.question = QtWidgets.QLabel(Save_question)
        self.question.setGeometry(QtCore.QRect(20, 10, 311, 51))
        self.question.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.question.setObjectName("question")
        self.yes_btn = QtWidgets.QPushButton(Save_question)
        self.yes_btn.setGeometry(QtCore.QRect(120, 70, 75, 23))
        self.yes_btn.setObjectName("yes_btn")
        self.no_btn = QtWidgets.QPushButton(Save_question)
        self.no_btn.setGeometry(QtCore.QRect(210, 70, 75, 23))
        self.no_btn.setObjectName("no_btn")

        self.retranslateUi(Save_question)
        QtCore.QMetaObject.connectSlotsByName(Save_question)

    def retranslateUi(self, Save_question):
        _translate = QtCore.QCoreApplication.translate
        Save_question.setWindowTitle(_translate("Save_question", "Form"))
        self.question.setText(_translate("Save_question", "Do you want to save the marked up image?"))
        self.yes_btn.setText(_translate("Save_question", "Yes"))
        self.no_btn.setText(_translate("Save_question", "No"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Save_question = QtWidgets.QWidget()
    ui = Ui_Save_question()
    ui.setupUi(Save_question)
    Save_question.show()
    sys.exit(app.exec_())
